# The Docker Config version. Do not change.
version: "3.1"

services: 
  server: 
    build: server/
    volumes: 
    - ./server:/src/app
    ports: 
      - "8080:8080"
    networks:
      - app-network 
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/greetings
    depends_on:
      - db

  frontend:
    build: frontend/docker-front/
    volumes:
    - ./frontend/docker-front:/src/app
    ports: 
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server



  db:
    image: postgres:latest
    container_name: db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: greetings
    volumes:
      - ./server/database:/var/lib/postgresql/data
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
